Workflow to Pull from Upstream and Cherry-pick Patches
opendatahub-io/odh-automation-serving pull request #4
Opened 2024-06-25 10:08 UTC by rpancham

**Pull from Upstream + Cherry-Pick a Series of Patches**
Incorporate the latest updates from the upstream repository while selectively integrating specific patches using the cherry-pick process.

We need a PAT_TOKEN of the repo odh-automation-serving to execute the workflow as normal github token doesn't work here as we are trying to run the workflow from another repository.

Issue : [RHOAIENG-8833](https://issues.redhat.com/browse/RHOAIENG-8833)

2024-07-01 18:30 UTC, Xaenalt requested changes

2024-07-01 18:30 UTC, Xaenalt commented on .github/workflows/pull_upstream_with_cherrypick.yml
> +          --body "$(echo -e "This is a auto genrated PR, Creating from odh-automation-serving\nCherry-pick of commits ${{ github.event.inputs.patch_commits }} into ${{ github.event.inputs.target_bran
Good use of gh CLI

2024-07-01 18:30 UTC, Xaenalt commented on .github/workflows/pull_upstream_with_cherrypick.yml
> +      upstream_repo:
These seem to target midstream, not an upstream repo

2024-07-01 18:30 UTC, Xaenalt commented on .github/workflows/pull_upstream_with_cherrypick.yml
> +        echo "midstream_org_repo=red-hat-data-services/${{ github.event.inputs.upstream_repo }}" >> $GITHUB_OUTPUT
opendatahub-io is midstream, red-hat-data-services is a downstream

In this case, the intent of the workflow is to take from upstream, and cherry-pick a series of commits on top of it, then merge that to a target repo+branch

2024-07-01 18:30 UTC, Xaenalt commented
Also this PR has a lot of overlap with #3

2024-07-03 09:25 UTC, rpancham commented
Yes Sean but the slight differnce is i am trying to pull from upstream to sync the repo and then cherry-picking the patches.
We can also combine the workflow as in my workflow i am pushing it so we can keep only one wokflow ? wdyt??

2024-07-11 14:12 UTC, Xaenalt approved these changes

2024-07-11 14:12 UTC, Xaenalt commented
/lgtm

2024-07-25 16:15 UTC, merged